module.exports = messages = {
    VALIDATION_MESSAGE: 'Please enter the details first',
    EDIT_COMPANY_MESSAGE: 'Company edited successfully',
    ERROR_MESSAGE: "Error occurred",
    EDIT_LOGO_MESSAGE: "Logo edited successfully",
    EDIT_SECURITY_MESSAGE: "Security details edited successfully",
    EDIT_STAMP_MESSAGE:"Stamp details edited successfully",
    EDIT_BRAND_MESSAGE:"Brand details edited successfully",
    FILE_UPLOAD:"File uploaded successfully",
    EDIT_ESIGN_MESSAGE:"Esign details edited successfully",
    EDIT_INVITE_MESSAGE: "Invite details edited successfully",
    REFRESH_TOKEN_MESSAGE: "Refresh token successfully",
    ADD_TEMPLATE_MESSAGE:"Template added successfully",
    EDIT_TEMPLATE_MESSAGE:"Template edited successfully",
    ERROR_TEMPLATE_MESSAGE:"Name already exists",
    DELETE_TEMPLATE_MESSAGE:"Template deleted successfully",
    EMAIL_VERIFICATION_MESSAGE:"Please verify your email",
    EMAIL_DUPLICATE_ERROR:"Email already exists",
    CODY_COPY: "Token copied successfully",
    SALT_COPY:"Salt copied successfully",
    EDIT_DOCUMENT_MESSAGE: "Details updated successfully",
    SALT_MESSAGE: "Private salt refresh successfully",
    SENT_MAIL: "Otp successully sent on email",
    NOT_FOUND: "Email not found",
    DELETE_DATA : "Deleted successfully",
    SUCCESS_MESSAGE : "Sent successfully",
    UPDATE_MESSAGE : "Updated successfully",
    MISMATCH_ERROR : "Mismatched password",
    VALIDATION_ERROR : "Mismatched confirm password",
    DELETE_VALIDATION_MESSAGE : "Atleast one invitee is required.",
    DUPLICATE_MESSAGE:  "Invitee detials already present",
    INVITEE_DETAILS: "Invitee details updated successfully",
    INVITEE_INFO: "Please fill the details",
    LINK_EXPIRED : "Link expired",
    SIGNATURE_VALIDATION : "Select atleast one signature type",
    SIGNED_ALREADY : "Document is already signed",
    IP_VALIDATION_MESSAGE : "Invalid IP address",
    PASSWORDNOT_OK: "You have to enter at least 5 digit!",
    ADDIP_MESSAGE: "Add IPs First",
    MAIL_SENT: "Details Sent"
}